# Generated by Django 5.2.7 on 2025-11-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gift_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Stock', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Gift_image', models.ImageField(blank=True, null=True, upload_to='gift_images')),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
