# Generated by Django 5.2.7 on 2025-11-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdb',
            old_name='confirm_password',
            new_name='Confirm_password',
        ),
        migrations.RenameField(
            model_name='registrationdb',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='registrationdb',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='registrationdb',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='registrationdb',
            old_name='phone',
            new_name='Phone',
        ),
    ]
