# Generated by Django 5.2.7 on 2025-11-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_contactdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='subject',
            new_name='Subject',
        ),
    ]
