# Generated by Django 5.2.7 on 2025-12-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='TotalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
